controller_list:
  - name: fake_fr5v6_controller
    type: $(arg execution_type)
    joints:
      - j1
      - j2
      - j3
      - j4
      - j5
      - j6
initial:  # Define initial robot poses.
  - group: fr5v6
    pose: zero